### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by francescomambrini** [grew-nlp/grew_match_quick#1]
When I run the `grew_match_quick.py` scritpt (e.g. with `python3 grew_match_quick.py corpus_folder `), the server is working and I see the basic corpus statistics, such as how many trees and tokens there are or the relation table.
However, when I try to run a query I get a `Connection fail. The search service is not available` error.

Here is the full content of `backend.stderr`:

```
File "gmb_main.eliom", line 435, characters 8-79:
435 |         {Session.graph_index; pos_in_graph; nb_in_graph; sent_id; matching}:: x)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: This expression should not be a list literal, the expected type is
       'a list -> 'a list
make: *** [Makefile:153: _server/gmb_main.type_mli] Error 2
```
I am using Ubuntu 20.04.

Thank you!

**Comment by bguil** [comment]
Thanks for the feedback @francescomambrini.

This should be fixed by [this commit](https://gitlab.inria.fr/grew/grew_match_back/-/commit/e288d680ef02f49074995e8b150b07d750d4b548).
Just run the python script again. It should take care about the `git pull`.
